baseurl: "/jekyll_warehouse"
safe: false
permalink: /posts/:title.html

exclude:
  - README.md

name: 符海飞的资源仓库（Jekyll版）
#host:
desc: 这是符海飞的资源仓库，用来存放常用IT软件，学习资料等，大家自取！感觉不错的话,记得给我留言哦 ~ ~ ~

custom:
    category:
        a: 专业软件
        b: 日常软件
        c: 电脑装机资源
        d: 电脑技术知识
        e: 学习资料
        f: 教学视频(及对应资料)
        g: 模板资源
        h: 游戏资源
        i: 视频资源
        j: 其他资源
    categories:
      - name:  a
        title: 专业软件

      - name:  b
        title: 日常软件

      - name:  c
        title: 电脑装机资源

      - name:  d
        title: 电脑技术知识

      - name:  e
        title: 学习资料

      - name:  f
        title: 教学视频(及对应资料)

      - name:  g
        title: 模板资源

      - name:  h
        title: 游戏资源

      - name:  i
        title: 视频资源

      - name:  j
        title: 其他资源


    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: 符海飞
        email: my@fuhaifei.xyz
        gcse: 013302542177053906402:2z8geqn8gr4     # Google自定义搜索标识ID
        github: turkey321                           # GitHub账号

    gapi: http://www.google.com/jsapi               # Google API地址
