# Site settings
title: NPM
email: 15751158939@163.com
description: NPM团队网站 前端爱好者
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  turkey321
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 9
paginate_path: "page:num"

# highlight
# 本地用rouge, github上用pygments
#highlighter: pygments
#highlighter: rouge
# highlighter: false
